# Generated by Django 3.1.7 on 2021-05-26 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Penduduk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kk', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=200)),
                ('nama_lengkap', models.CharField(max_length=200)),
                ('stat_hbkel', models.CharField(blank=True, choices=[('kepala Keluarga', 'kepala Keluarga'), ('Istri', 'Istri'), ('Anak Kandung', 'Anak kandung'), ('Cerai Mati', 'Cerai Mati'), ('Cerai Hidup', 'Cerai Hidup')], max_length=200, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True)),
                ('tanggal_lahir', models.CharField(max_length=200)),
                ('dusun', models.CharField(blank=True, choices=[('Dusun Matikan', 'Dusun Matikan'), ('Dusun Krajan', 'Dusun Krajan'), ('Dusun Kejawan', 'Dusun Kejawan')], max_length=200, null=True)),
                ('no_rt', models.CharField(max_length=200)),
                ('no_rw', models.CharField(max_length=200)),
                ('kode_pos', models.CharField(max_length=200)),
                ('keterangan', models.CharField(blank=True, choices=[('Kelahiran', 'Kelahiran'), ('Kematian', 'Kematian'), ('Penduduk Tetap', 'Penduduk Tetap')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Penduduk',
            },
        ),
    ]
