# Generated by Django 3.1.7 on 2021-05-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0002_penduduk_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='penduduk',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('Pelajar/Mahasiswa', 'Pelajar/Mahasiswa')], max_length=200, null=True),
        ),
    ]
