# Generated by Django 3.1.7 on 2021-06-09 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0006_remove_sku_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sku',
            new_name='Surat',
        ),
        migrations.AlterModelOptions(
            name='surat',
            options={'verbose_name_plural': 'Surat'},
        ),
    ]
