# Generated by Django 3.1.7 on 2021-06-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0007_auto_20210609_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='penduduk',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
