# Generated by Django 3.1.7 on 2021-06-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0010_penduduk_desa'),
    ]

    operations = [
        migrations.AddField(
            model_name='penduduk',
            name='status_perkawinan',
            field=models.CharField(blank=True, choices=[('Kawin', 'Kawin'), ('Belum Kawin', 'Belum Kawin')], max_length=200, null=True),
        ),
    ]
