# Generated by Django 3.1.7 on 2021-06-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0011_penduduk_status_perkawinan'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='desa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='surat',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
