# Generated by Django 3.1.7 on 2021-06-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0012_auto_20210620_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='status_perkawinan',
            field=models.CharField(blank=True, choices=[('Kawin', 'Kawin'), ('Belum Kawin', 'Belum Kawin')], max_length=200, null=True),
        ),
    ]
