# Generated by Django 3.1.7 on 2021-06-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0013_surat_status_perkawinan'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='jenis_usaha',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
