# Generated by Django 3.1.7 on 2021-06-24 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0014_surat_jenis_usaha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis_Surat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_surat', models.CharField(max_length=200)),
                ('jenis_surat', models.CharField(blank=True, choices=[('Surat Keterangan Usaha', 'Surat Keterangan Usaha'), ('Surat Keterangan KTP', 'Surat Keterangan KTP'), ('Surat Keterangan Kematian', 'Surat Keterangan Kematian'), ('Surat Keterangan Kelahiran', 'Surat Keterangan Kelahiran'), ('Surat Keterangan skck', 'Surat Keterangan skck'), ('Surat Keterangan penduduk tetap', 'Surat Keterangan penduduk tetap'), ('Surat Keterangan Pindah', 'Surat Keterangan Pindah'), ('Surat Keterangan KTP', 'Surat Keterangan KTP')], max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Jenis_Surat',
            },
        ),
    ]
