# Generated by Django 3.1.7 on 2021-06-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0015_jenis_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='nik',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_kk',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_rt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_rw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='tanggal_lahir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
