# Generated by Django 3.1.7 on 2021-06-28 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0016_auto_20210628_0939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis_surat',
            name='no_surat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
