# Generated by Django 3.1.7 on 2021-07-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0017_auto_20210628_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='keterangan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),

        migrations.AlterField(
            model_name='surat',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nik',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_rt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_rw',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_surat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal_lahir',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
