# Generated by Django 3.1.7 on 2021-07-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0018_auto_20210712_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='jenis_surat',
            name='keterangan_jenis',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
