# Generated by Django 3.1.7 on 2021-07-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0019_jenis_surat_keterangan_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis_surat',
            name='jenis_surat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
