# Generated by Django 3.1.7 on 2021-07-17 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0020_auto_20210712_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jenis_surat',
            name='keterangan_jenis',
        ),
    ]
