# Generated by Django 3.1.7 on 2021-07-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0021_remove_jenis_surat_keterangan_jenis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis_surat',
            name='jenis_surat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='jenis_surat',
            name='no_surat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='desa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='dusun',
            field=models.CharField(blank=True, choices=[('Dusun Matikan', 'Dusun Matikan'), ('Dusun Krajan', 'Dusun Krajan'), ('Dusun Kejawan', 'Dusun Kejawan')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='keterangan',
            field=models.CharField(blank=True, choices=[('Kelahiran', 'Kelahiran'), ('Kematian', 'Kematian'), ('Penduduk Tetap', 'Penduduk Tetap')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_kk',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_rt',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_rw',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('Pelajar/Mahasiswa', 'Pelajar/Mahasiswa')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='stat_hbkel',
            field=models.CharField(blank=True, choices=[('kepala Keluarga', 'kepala Keluarga'), ('Istri', 'Istri'), ('Anak Kandung', 'Anak kandung'), ('Cerai Mati', 'Cerai Mati'), ('Cerai Hidup', 'Cerai Hidup')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='status_perkawinan',
            field=models.CharField(blank=True, choices=[('Kawin', 'Kawin'), ('Belum Kawin', 'Belum Kawin')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='tanggal_lahir',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='desa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='dusun',
            field=models.CharField(blank=True, choices=[('Dusun Matikan', 'Dusun Matikan'), ('Dusun Krajan', 'Dusun Krajan'), ('Dusun Kejawan', 'Dusun Kejawan')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='jenis_kelamin',
            field=models.CharField(blank=True, choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='jenis_surat',
            field=models.CharField(blank=True, choices=[('Surat Keterangan Usaha', 'Surat Keterangan Usaha'), ('Surat Keterangan KTP', 'Surat Keterangan KTP'), ('Surat Keterangan Kematian', 'Surat Keterangan Kematian'), ('Surat Keterangan Kelahiran', 'Surat Keterangan Kelahiran'), ('Surat Keterangan skck', 'Surat Keterangan skck'), ('Surat Keterangan penduduk tetap', 'Surat Keterangan penduduk tetap'), ('Surat Keterangan Pindah', 'Surat Keterangan Pindah'), ('Surat Keterangan KTP', 'Surat Keterangan KTP')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='jenis_usaha',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='keterangan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_rt',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_rw',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_surat',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='pendidikan',
            field=models.CharField(blank=True, choices=[('SD', 'SD'), ('SLTP', 'SLTP'), ('SLTA', 'SLTA'), ('Pelajar/Mahasiswa', 'Pelajar/Mahasiswa')], max_length=35, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='status_perkawinan',
            field=models.CharField(blank=True, choices=[('Kawin', 'Kawin'), ('Belum Kawin', 'Belum Kawin')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tanggal_lahir',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
