# Generated by Django 3.1.7 on 2021-07-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0022_auto_20210721_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='kode_pos',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
