# Generated by Django 3.1.7 on 2021-07-28 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0023_auto_20210721_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='tanggal',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
