# Generated by Django 3.1.7 on 2021-08-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0026_surat_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='no_telp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
