# Generated by Django 3.1.7 on 2021-08-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0028_auto_20210801_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='surat',
            name='bulan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
