# Generated by Django 3.1.7 on 2021-08-02 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0029_surat_bulan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mayarakat',
            options={'verbose_name_plural': 'Masyarakat'},
        ),
    ]
