# Generated by Django 3.1.7 on 2021-08-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0032_auto_20210802_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='nik',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
