# Generated by Django 3.1.7 on 2021-08-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0033_auto_20210802_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='nik',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
