# Generated by Django 3.1.7 on 2021-08-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0034_auto_20210802_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='no_kk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
