# Generated by Django 3.1.7 on 2021-08-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0035_auto_20210802_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='kode_pos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_rt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='no_rw',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_rt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='no_rw',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
