# Generated by Django 3.1.7 on 2021-08-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0036_auto_20210802_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penduduk',
            name='nik',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
