# Generated by Django 3.1.7 on 2021-08-06 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0037_auto_20210803_0305'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mayarakat',
            new_name='Masyarakat',
        ),
    ]
