# Generated by Django 3.1.7 on 2021-08-06 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surat', '0039_auto_20210807_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saya',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_petugas', models.CharField(max_length=50)),
                ('nip_petugas', models.CharField(max_length=18)),
                ('tempat_lahir_petugas', models.CharField(max_length=50)),
                ('pendidikan_petugas', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('alamat', models.CharField(max_length=100)),
                ('no_hp', models.CharField(max_length=12)),
                ('sk_angkatan', models.CharField(max_length=30)),
                ('tanggal_angkatan', models.CharField(max_length=30)),
                ('sk_terakhir', models.CharField(max_length=30)),
                ('tanggal_terakhir', models.CharField(max_length=30)),
                ('foto_petugas', models.ImageField(blank=True, default='fotokosong.jpg', upload_to='')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saya',
            },
        ),
    ]
