# Generated by Django 3.1.7 on 2021-08-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0040_saya'),
    ]

    operations = [
        migrations.AddField(
            model_name='penduduk',
            name='BULAN',
            field=models.CharField(blank=True, max_length=35, null=True),
        ),
    ]
