# Generated by Django 3.1.7 on 2021-08-06 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0043_auto_20210807_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penduduk',
            name='BULAN',
        ),
    ]
