# Generated by Django 3.1.7 on 2021-08-07 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0044_remove_penduduk_bulan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masyarakat',
            old_name='jenis_usaha',
            new_name='keperluan',
        ),
        migrations.RemoveField(
            model_name='surat',
            name='JENIS_USAHA',
        ),
        migrations.AddField(
            model_name='surat',
            name='KEPERLUAN',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='KETERANGAN',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
