# Generated by Django 3.1.7 on 2021-08-09 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0048_auto_20210809_0943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='masyarakat',
            old_name='keperluan',
            new_name='catatan',
        ),
    ]
