# Generated by Django 3.1.7 on 2021-08-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0049_auto_20210809_0946'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='surat',
            name='TANGGAL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
