# Generated by Django 3.1.7 on 2021-08-10 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0050_auto_20210810_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surat',
            name='NO_KK',
        ),
    ]
