# Generated by Django 3.1.7 on 2021-08-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0051_remove_surat_no_kk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masyarakat',
            name='no_telp',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='ALAMAT',
            field=models.CharField(blank=True, choices=[('DUSUN KEJAWAN', 'DUSUN KEJAWAN'), ('DUSUN MATIKAN', 'DUSUN MATIKAN'), ('DUSUN KRAJAN', 'DUSUN KRAJAN')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='KETERANGAN',
            field=models.CharField(blank=True, choices=[('MENINGGAL', 'MENINGGAL'), ('PINDAH', 'PINDAH')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='NIK',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='NO_KK',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='NO_RT',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='penduduk',
            name='NO_RW',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='BULAN',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='KETERANGAN',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='NIK',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='NM_KEC',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='NM_KEL',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='NO_RT',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='NO_RW',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='surat',
            name='TANGGAL',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
