# Generated by Django 3.1.7 on 2021-08-14 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0057_auto_20210813_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saya',
            name='foto_petugas',
        ),
        migrations.RemoveField(
            model_name='saya',
            name='sk_angkatan',
        ),
        migrations.RemoveField(
            model_name='saya',
            name='sk_terakhir',
        ),
        migrations.RemoveField(
            model_name='saya',
            name='tanggal_angkatan',
        ),
        migrations.RemoveField(
            model_name='saya',
            name='tanggal_terakhir',
        ),
    ]
