# Generated by Django 3.1.7 on 2021-08-15 02:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('surat', '0058_auto_20210815_0635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saya',
            new_name='Petugas',
        ),
        migrations.AlterModelOptions(
            name='petugas',
            options={'verbose_name_plural': 'Petugas'},
        ),
    ]
