# Generated by Django 3.1.7 on 2021-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surat', '0059_auto_20210815_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surat',
            name='JENIS_SURAT',
            field=models.CharField(blank=True, choices=[('Surat Keterangan Usaha', 'Surat Keterangan Usaha'), ('Surat Keterangan Tidak Mampu', 'Surat Keterangan Tidak Mampu'), ('Surat Keterangan Terdampak Covid', 'Surat Keterangan Terdampak Covid'), ('Surat Keterangan Penghasilan', 'Surat Keterangan Penghasilan'), ('Surat Keterangan Kematian', 'Surat Keterangan Kematian'), ('Surat Keterangan Kelakuan Baik', 'Surat Keterangan Kelakuan Baik'), ('Surat Keterangan Kehilangan', 'Surat Keterangan Kehilangan'), ('Surat Keterangan Domisili', 'Surat Keterangan Domisili')], max_length=50, null=True),
        ),
    ]
